# Build and test
name: BUild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        
      - name: Setup TypeScript
        run: npm i tsc
        
      - name: Compile TypeScript
        run: npx tsc --noEmit
