# Lint using ESLint
name: Lint

on:
  push:
    branches:
      - main
      - release/*
    paths: "src/**"
  pull_request:
    branches:
      - main
      - release/*
    paths: "src/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        
      - name: Setup ESLint
        run: npm i eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin
        
      - name: Lint ESLint project
        run: npx eslint .
