# Build and test
name: Build

on:
  push:
    branches: [ main ]
    paths: "src/**"
    
  pull_request:
    branches: [ main ]
    paths: "src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        
      - name: Setup TypeScript
        run: npm i typescript
        
      - name: Compile TypeScript
        run: npx tsc --noEmit
