# Build using TypeScript
name: Build

on:
  push:
    branches: 
      - main
      - release/*
    paths: src/**
    
  pull_request:
    branches: 
      - main
      - release/*
    paths: src/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        
      - name: Setup TypeScript
        run: npm i typescript @types/node
        
      - name: Build TypeScript project
        run: npx tsc --noEmit
